=== RaulHernandez12/ejercicios-lenguaje/XML/Concesionario xs/concesionario.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="concesionario">		
		<xs:complexType>
			<xs:sequence>
				<xs:element name="coche" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="marca" type="xs:string"/>
							<xs:element name="modelo" type="xs:string"/>
							<xs:choice>
								<xs:element name="cilindrada" type="xs:decimal"/>
								<xs:element name="caballos" type="xs:string"/>
							</xs:choice>
							<xs:element name="combustible" type="xs:string"/>
							<xs:element name="precio" type="xs:string"/>
							<xs:element name="aÃ±o" type="xs:string" minOccurs="0"/>
							<xs:element name="color" type="xs:string"/>
							<xs:element name="interesado" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="fecha_limite" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="fecha" type="xs:date" use="required"/>
								</xs:complexType>
							</xs:element>						
						</xs:sequence>
						
						<xs:attribute name="matricula" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>	
			</xs:sequence>
			<xs:attribute name="provincia" type="xs:string"/>
		</xs:complexType>
	
	</xs:element>
</xs:schema>

=== RaulHernandez12/ejercicios-lenguaje/XML/Concesionario xs/xml.xml
<?xml version="1.0" encoding="utf-8"?>
<concesionario
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="concesionario.xsd"
provincia="Malaga">
	<coche matricula="6732KPC">
		<marca>Seat</marca>
		<modelo>Ateca</modelo>
		<cilindrada>1.7</cilindrada>
		<combustible>Diesel</combustible>
		<precio>23.000€</precio>
		<año>2018</año>
		<color>negro</color>
		<interesado>33358697A</interesado>
		<interesado>305154557</interesado>
		<fecha_limite fecha="2022-02-12"/>
	</coche>
</concesionario>
