=== RaulHernandez12/ejercicios-lenguaje/XML/listaclientes/listaclientes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="listaclientes" type="tipolistaclientes"/>
	
		<xs:complexType name="tipolistaclientes">
			
			<xs:sequence>
				<xs:element name="cliente" type="tipocliente" maxOccurs="unbounded"/> 
			</xs:sequence>		
		
		</xs:complexType>
		<xs:complexType name="tipocliente">
			<xs:sequence>
				<xs:element name="nombre" type="xs:string"/>
				<xs:element name="apellidos" type="xs:string"/>
				<xs:choice>
					<xs:element name="dni" type="xs:string"/>
					<xs:element name="nie" type="xs:string"/>
				</xs:choice>
				<xs:element name="compras" type="tipocompras"/>
				<xs:element name="regalo" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="español" type="xs:string" use="required"/>
		</xs:complexType>
		
		<xs:simpleType name="tipodni">
			<xs:restriction base="xs:string">
				<xs:length value="9"/>
			</xs:restriction>		
		</xs:simpleType>
		
		<xs:simpleType name="tipocompras">
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="3000"/>
				<xs:maxInclusive value="5000"/>
			</xs:restriction>		
		</xs:simpleType>
		
		<xs:simpleType name="tipoespañol">
			<xs:restriction base="xs:string">
				<xs:enumeration value="si"/>
				<xs:enumeration value="no"/>
			</xs:restriction>		
		</xs:simpleType>

</xs:schema>

=== RaulHernandez12/ejercicios-lenguaje/XML/listaclientes/listaclientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaclientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="listaclientes.xsd">

	<cliente español="si">
		<nombre>Juan</nombre>
		<apellidos>Sanchez</apellidos>
		<dni>33355579X</dni>
		<compras>4300</compras>
		<regalo>bolsa deporte</regalo>
	</cliente>
	
	<cliente español="no">
		<nombre>Jose</nombre>
		<apellidos>Diaz</apellidos>
		<nie>C45678912T</nie>
		<compras>5500</compras>		
	</cliente>
	
</listaclientes>
